# Generated by Django 4.1.5 on 2023-11-17 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, null=True)),
                ('venue', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_one_runs', models.IntegerField(blank=True, null=True)),
                ('country_one_wickets', models.IntegerField(blank=True, null=True)),
                ('country_two_runs', models.IntegerField(blank=True, null=True)),
                ('country_two_wickets', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
