# Generated by Django 4.1.5 on 2023-11-17 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
        ('countries', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='man_of_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='players.player'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matches.match'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='runner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lost_results', to='countries.country'),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_results', to='countries.country'),
        ),
        migrations.AddField(
            model_name='match',
            name='country_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_country_one', to='countries.country'),
        ),
        migrations.AddField(
            model_name='match',
            name='country_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_country_two', to='countries.country'),
        ),
    ]
